### ISSUE TITLE
midi/in/cc default value not sent

### ISSUE THREAD

**Issue by timvets** [JohannesTaelman/axoloti#48]
When you set a default value in the midi/in/cc object, 
it is not sent to its outlet when going into live mode.
(or is this by design?)

**Comment by TheTechnobear** [comment]
looking at object, it should send default when created, and it doesnt
(to test, I simply hooked a in/cc to a disp p to see if it would change the value and it didn't)
Johannes, the init code is ccv=%default% where default is an attribute is this still correct?
(I'm thinking possible regression due to the removal of %name%) 

tim... do you know if this works on the master branch?

**Comment by timvets** [comment]
no, it doesn't work in the master branch either.

**Comment by TheTechnobear** [comment]
k, thanks... 
one thing I noticed on my test, was it appears to send zero when patch goes live.
(and this does not change even if you change the default of the attribute to something else)

also midi/in/cc i works as expected.
whats strange is that the generated code for cc and cc i looks the same ?! 
Im guessing some type conversion issue?

**Comment by TheTechnobear** [comment]
ok, got it... data type issue as suspected...
