### ISSUE TITLE
GUI: Typing space in a comment object triggers the object selector

### ISSUE THREAD

**Issue by JohannesTaelman** [JohannesTaelman/axoloti#97]

**Comment by TheTechnobear** [comment]
it doesn't for me on OS X...  
its funny, I actually had worried this might be the case a couple of days ago, so tested :)
(and retested now)

does it do it for any of the other shortcuts  e.g N?

**Comment by TheTechnobear** [comment]
got it... it appears to only do on edit.... gonna test some more

**Comment by JohannesTaelman** [comment]
n triggers it too

**Comment by TheTechnobear** [comment]
yup , quite serious as Ive put in quite a few more shortcuts on the editor... 
I'll take a look... I think we probably just have to take away 'focus' from the main panel

**Comment by TheTechnobear** [comment]
BTW: comments contents should not be the object id... it means you cannot have 2 comments the same :)

**Comment by JohannesTaelman** [comment]
also triggered when editing the instance name of an object

**Comment by TheTechnobear** [comment]
fixed... its actually only N... 
its was caused by me adding an accelerator to the menu, and it appears the menu is still active when then editor is active.
for the time being Ive removed... since we don't have accelerators for the other panel shortcuts.

we/if we do, then I think we will need to check the component that is active at the time
but seems low priority for the moment.
